- alembic/README.md
- core/README.md
Fixed a few typos to make the documentation clearer. Hope this helps.
> docs: fix minor typos

- README.md
Brief: Added details about where temporary files are stored for the NO_CACHE flag.
Problem: The README's note on NO_CACHE explains that it doesn't prevent downloads but does delete temporary files after processing. This is helpful, but it doesn't explain where these files are stored even temporarily. This can lead to confusion about storage usage.
Solution: Specify the location of the temporary files (./data directory) to give users a concrete understanding of where disk space is being used, even temporarily.
> Clarify NO_CACHE flag in README

- api/src/handlers.rs
Summary
This pull request introduces two major improvements to the API:
1. **Pagination for `/tables`:** The route now supports `page` and `limit` query parameters, returning paginated results with metadata such as `total_count`, `page`, and `total_pages`.
2. **Enhanced 404 Error Responses:** Refactored table existence checks into a reusable `check_table_exists` utility function. The 404 responses now include valid table suggestions and a link to API documentation for improved client experience.
Changes
- Updated `/tables` to support pagination.
- Centralized table existence checks.
- Improved error messages for invalid table names.
Benefits
- Scalable API for large datasets.
- Consistent and user-friendly error handling.
> feat(api): Add pagination and enhance error handling

- alembic/Dockerfile
Fixes an issue where the alembic container would fail to start on Docker Desktop for Windows due to script execution problems
- Updated `alembic/Dockerfile` to explicitly use `/bin/sh` when executing the migration script
Fixes #40
> Fix alembic container by explicitly use /bin/sh to execute migration script

- package_managers/crates/transformer.py
Summary  
This pull request refactors the `CratesTransformer` class to improve code reusability, error handling, and maintainability by introducing a helper method for reading CSV files.
Changes  
1. Added a `_read_csv_rows` helper method to centralize the logic for opening and reading CSV files.  
2. Updated all methods (`packages`, `versions`, `dependencies`, `users`, `user_packages`, `user_versions`, `urls`, and `package_urls`) to use the new `_read_csv_rows` method.  
3. Improved error handling with `try-except` blocks to log detailed errors if a file is missing or invalid.  
4. Refined the logic for handling optional fields like `homepage`, `repository`, and `documentation` to strip whitespace and prevent potential issues with empty strings.  
5. Enhanced deduplication in the `users` …
> Abstract and reuse the method for reading CSV.

- examples/visualizer/main.py
Adds error handling for database connections in the `DB` class in `examples/visualizer/main.py`.
Validates the presence of the `CHAI_DATABASE_URL` environment variable before attempting a connection.
Wraps the `psycopg2.connect` call in a `try-except` block to provide meaningful error messages when a connection fails.
Prevents unexpected crashes when the database connection fails or `CHAI_DATABASE_URL` is not set.
Provides clear, actionable feedback to the user.
Added a validation step for `CHAI_DATABASE_URL`.
Added error handling for `psycopg2.OperationalError` during database connection.
> fix: Add error handling for database connection

- examples/visualizer/main.py
Graphviz uses the American spelling of the color “gray” instead of the British spelling “grey”. Using “grey” may cause Graphviz to not recognize the color and apply the default value or generate an error.
> Fix logic error in main.py

- README.md
I’ve corrected the capitalization of "API" in the Docker Services Overview.
The term "**API**" is typically written in all caps, so I’ve updated it to match that standard for consistency and clarity.
> docs: Fix capitalization of "API" in Docker Services Overview

- api/Dockerfile
- api/src/handlers.rs
**Description**
- Replaced `map_or(false, |e| ...)` with `.is_some_and(...)` for checking database errors.
- Simplifies the logic and aligns with Clippy’s suggestions.
**Why**
- This makes the code more readable and concise.
- Resolves the Clippy warning about `unnecessary_map_or`.
> Use is_some_and instead of map_or(false) for database error checks

- tests/unit/test_rx_graph.py
fixed a bug where tolerance was being checked inconsistently.
now the absolute deviation is correctly computed using `abs(...)`, and the comparison stays fully within the Decimal system. 
this ensures precise behavior when dealing with small tolerances, which is especially important for accuracy-sensitive calculations.
> fix: incorrect tolerance check using `abs` with Decimal

- scripts/chai-legacy-loader/add_package_fields.py
noticed that the script name was hardcoded as `script.py`.
replaced it with a dynamic value to make the interface cleaner and more flexible.
small change, but improves maintainability and aesthetics :)
> fix: hardcoded script name in UI tweak

- .github/workflows/chai-api.ci.yml
- .github/workflows/ci.yml
Hey ! GitHub‑hosted runners now use Node 20, so checkout v4 is required
This PR updates all workflows to actions/checkout@v4 , no functional changes expected
> ci: bump actions/checkout to v4

- scripts/package_to_package/package_dependencies.py
- tests/requirements.txt
- tests/scripts/package_to_package/test_package_dependencies.py
- works by invoking it directly `scripts/package_to_package/package_dependencies.py --package-manager homebrew`
- it grabs the latest version per package, and loads that into the `LegacyDependsOn` table
- plan to rename `LegacyDependsOn` to `DependsOn` once all the indexers are updated to load to that table
- few more PRs will be incoming to load the Legacy Depends On table directly
- loading dependencies will now be a destructive operation too, since we're looking at the latest version's dependencies only --- if an older version depended on foo, and the latest one doesn't, we should remove the foo dependency.
> migration script for existing data to a package package dependency model

- .github/workflows/deploy.yml
- Replace `actions/checkout@v3` with `actions/checkout@v4` in `.github/workflows/deploy.yml`
- Brings Node 20 runtime, faster fetch-depth handling, and recent security fixes
[Ref](https://github.com/actions/checkout#checkout-v4)
> ci: upgrade actions/checkout to v4 in deploy workflow

- alembic/versions/20250508_1752-add_trgm_indexes.py
- core/models/__init__.py
adding trgm indexes on the fields that the tea app uses to search for CHAI projects, to improve efficiency of the search. note that this is a stopgap, and we should probs investigate:
- bigram extension
- dedicated search columns with their own indexes
for now, this does result in a pretty significant improvement in the query planner's cost estimation for running the search query using a wildcard on the canons and URLs table.
> add trgm indexes

- alembic/versions/20250529_2341-rename_canons_table_and_recreate.py
- alembic/versions/20250529_2345-recreate_canon_foreign_keys.py
- core/models/__init__.py
Another one related to #93.
Achieves the dependency from canons to URLs. This should've always been a canons to `url_id` table, so this adjusts the design flaw by making it consistent with the rest of our table structures. I've broken out the migration into two steps because:
1. Renames old table to canons_old, removes all foreign key constraints, and creates the new canons table so we're ready to load it using our deduplicator script
2. Re-establishes all the foreign keys
1. We'll need to run the dedupe.py script to load new canons 
2. We'll need to truncate canon_packages and old tea_ranks
2 won't be an issue because the way we're conceptualizing the graph is not changing, just the structure of the table.
> two-step migration for new canons

- README.md
* **Old version:** `docker-compose` (with a hyphen) – this was the older command that required a separate installation of the `docker-compose` tool.
* **New version (recommended):** `docker compose`  – this is the modern, official Docker CLI syntax supported since Docker version 20.10.
So always use:
```sh
docker compose restart api
```
> docs (README.md): change command to restart-api

- core/db.py
- package_managers/homebrew/db.py
- package_managers/homebrew/main.py
- package_managers/pkgx/db.py
- package_managers/pkgx/main.py
- tests/package_managers/pkgx/test_pkgx_diff.py
- ruff
- DRY ingests and centralize setting URLs
> DRY ingests

- README.md
**Enable selective package manager runs via `PACKAGE_MANAGER=<name> docker compose up`**
This PR introduces a cleaner way to run **only one package manager** pipeline at a time by using an environment variable:
```sh
PACKAGE_MANAGER=<name> docker compose up
```
---
Previously, docs or examples suggested:
```sh
docker compose up -e PACKAGE_MANAGER=<name>
```
This syntax is **invalid** in Docker Compose — `-e` is **not a valid flag** for `docker compose up`. This caused confusion and led to incorrect execution or failure to inject the environment variable properly.
---
By exporting the variable *inline* before the command, Docker correctly injects `PACKAGE_MANAGER` into the container environment:
```sh
PACKAGE_MANAGER=crates docker compose up
```
This approach works **as long as** …
> Fix incorrect Docker Compose usage for single package manager

- api/src/handlers.rs
all leaderboard queries without project id limits.
Approximately 250ms to query the top 100.
> add leaderboard-all

- api/src/handlers.rs
```json
{
"dependenciesCount": 29,
"dependentsCount": 1,
"homepage": "github.com/andy-shea/redux-formalize",
"name": "redux-formalize",
"packageManagers": [
"npm"
],
"projectId": "5cfc3fa4-f04a-417a-a0be-b09a1380b033",
"source": "github.com/andy-shea/redux-formalize",
"teaRank": "0",
"teaRankCalculatedAt": null
}
```
quick bc we already have all the necessary indexes, no need for materialized views or anything yet. i've also only added the data point to the `/project/:id` endpoint
> add dependencies / dependents count to /project
